spring:
  application:
    name: finalEclips
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@nextit.or.kr:21521:xe
    username: team202408_01
    password: oracle21c
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 94365936844-3dnf5tj6l0k9et5e1897725648fcc9a9.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile
              - email
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: chakannyeoseok@gmail.com
    password: tipi xcga nogn kciw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: NULL

jwt:
  secret: 6364b0d2de554d3e942b1b8b048345251ce116d2a7264276973bb342f0e55def
  iss: nextit.or.kr
  sub: myapp-jwt
  expiration-milliseconds: 86400000 # 만료기한 1일

cookie:
  jwt:
    name: Authorization
    http-only: false
    secure: false
    path: /
    maxAge: 604800
    

