spring:
  application:
    name: finalEclips
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@nextit.or.kr:21521:xe
    username: team202408_01
    password: oracle21c
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 94365936844-3dnf5tj6l0k9et5e1897725648fcc9a9.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile
              - email

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: NULL

jwt:
  secret: 6364b0d2de554d3e942b1b8b048345251ce116d2a7264276973bb342f0e55def
  iss: nextit.or.kr
  sub: myapp-jwt
  expiration-milliseconds: 86400000 # 만료기한 1일

cookie:
  jwt:
    name: Authorization
    http-only: false
    secure: false
    path: /
    maxAge: 604800