spring:
  application:
    name: finalEclips
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@nextit.or.kr:21521:xe
    username: team202408_01
    password: oracle21c
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: NULL
attachment:
  dir-path: "C://attachments"
